# Generated by Django 5.2.3 on 2025-07-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
    ]
