# Generated by Django 5.2.3 on 2025-07-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_description_product_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
    ]
